# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Deploy

on: [ push ]
#  push:
#    branches: [ main , i ]
#  pull_request:
#    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: git commnad
      uses: garygrossgarten/github-action-ssh@release
      with:
        command: ${{ secrets.CMD }}
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        privateKey: ${{ secrets.PRIVATE_KEY}}